name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Format
        run: make format

      - name: Run tests
        env:
          ENV_STATE: TEST
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ML_PRICER_MODEL_PATH : ./PricerMlModel/models/price_model.pkl
          ML_PRICER_RAW_DATA_PATH : ./PricerMlModel/data/raw/retail_price.csv
          ML_PRICER_TRAIN_DATA_PATH : ./PricerMlModel/data/preprocessed/train.csv
          ML_PRICER_TEST_DATA_PATH : ./PricerMlModel/data/preprocessed/test.csv
          ML_PRICER_MODEL_VERSION : "V1"
          ML_PRICER_METRICS_PATH : ./PricerMlModel/reports/metrics.json 
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          REFRESH_TOKEN_EXPIRE_DAYS: 7
        run: make test-report

      - name: Generate Coverage Report Summary
        if: always()
        run: |
          echo "### Code Coverage Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`text" >> $GITHUB_STEP_SUMMARY
          coverage report -m >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      # 3. Create an optional HTML report to bundle up and download from the build artifacts panel
      - name: Build HTML Coverage Report File
        if: always()
        run: coverage html

      - name: Upload HTML Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/